### ISSUE TITLE
Multiplayer "Hot Seat" is broken

### ISSUE THREAD

**Issue by JHCD** [CQUI-Org/cqui#468] opened 2017-04-01 15:54 UTC
While I merged the _Spring 2017 Patch_ into CQUI I saw that some multiplayer parts are missing in the CQUI files (mainly reset variables when playerID changed).

I haven't dona a full search for this multiplayer stuff but I have started a _Hot Seat_ game and some issues arisen. Here we have a ToDo.

**Comment by chaorace** [comment] 2017-04-01 18:25
Duplicate of #271?

**Comment by JHCD** [comment] 2017-04-01 18:29
I would say #271 is one problem of this general task, yes...

You have problems with icons etc. too... 
e.g.: selecting settler as player 1 - change - settler-lens is active for player 2

**Comment by chaorace** [comment] 2017-04-01 19:05
I think it makes more sense to merge this issue into #271

**Closed** 2017-04-01 19:07 UTC
Labels: bug, low priority
