### ISSUE TITLE
When you capture a city the city will automatically be yours no need for negotiation

### ISSUE THREAD

**Issue by gelodgreat** [CQUI-Org/cqui#475] opened 2017-04-03 13:22 UTC
When you capture a city the city will automatically be yours no need for negotiation
![1](https://cloud.githubusercontent.com/assets/20021423/24611050/657a5bb0-18b3-11e7-8f6f-a38dce951a98.png)
![2](https://cloud.githubusercontent.com/assets/20021423/24611049/65194c94-18b3-11e7-871a-37967a96cab2.png)

**Comment by ricanuck** [comment] 2017-04-03 15:57
Whenever you try to negotiate peace BEFORE selecting KEEP CITY, the DealManager does not know what to do and you see what you see here... make your selection to KEEP CITY first and then you will see the Cede/Return option in diplo deal view.

NOT a bug. (not CQUI's anyways, you may consider it a bug in vanilla, although it's hard to argue for that as the selection to keep a city or not should logically come before the negotiation).

**Comment by chaorace** [comment] 2017-04-03 18:06
Indeed, closing issue

**Closed by chaorace** 2017-04-03 18:06 UTC
